blog/urls.py
from django.urls import path
from . import views
#se importa url views a busqueda de directorio raiz blog
urlpatterns = [
    
    
    path('',views.blog,name='blog'),
    #se agrega visualizacion de categoria por lectura de bbdd
    path('categoria/<categoria_id>',views.categoria,name='categoria')
    

]

carro/urls.py
from django.urls import path

from . import views
#se importa config para visualizacion de imagenes
app_name='carro'

urlpatterns = [
    
    
    path('agregar/<int:producto_id>/',views.agregar_producto,name='agregar'),
    path('eliminar/<int:producto_id>/',views.eliminar_producto,name='eliminar'),
    path('restar/<int:producto_id>/',views.restar_producto,name='restar'),
    path('limpiar/',views.limpiar_carro,name='limpiar'),

    

]

proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/',include('carro.urls')),

    #importo las urls del proyectoWebApp
    path('',include('ProyectoWebApp.urls')),
]

tienda/urls.py
from django.urls import path

from . import views
#se importa config para visualizacion de imagenes

urlpatterns = [
    
    
    path('',views.tienda,name='tienda'),
    

]

tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriaProd'
        verbose_name_plural = 'categoriasProd'
    
    def __str__(self):
        return self.nombre

    

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd,on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda",null=True,blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        
    

tienda/views.py
from django.shortcuts import render
from . models import Producto

# Create your views here.
def tienda(request):

    Productos=Producto.objects.all()

    return render(request,"tienda/tienda.html",{"productos":Productos})

tienda/templates/tienda/tienda.html
{% extends "ProyectoWebApp/base.html" %} {% load static %} {% block content %}
<div class="container">
    <div style="float:right">

        {% include "carro/widget.html" %}

    </div>

    <div class="row">
        {% for producto in productos %}
        <div class="col-md-3">
            <div class="card" style="width: 100%;margin: 5px 5px;">
                <img src="{{producto.imagen.url}}" class="card-img-top">
                <div class="card-body" style="text-align: center;">

                    <h7 class="card-title">{{producto.nombre}}</h7>
                    <p class="card-text">{{producto.precio}}&nbsp;$</p>

                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success"> agregar al carro</a>

                </div>
            </div>
        </div>






        {% endfor %}
    </div>
</div>
{% endblock %}